spring:
  data:
    mongodb:
      uri: mongodb://192.168.31.99/rainbow_api_server
  datasource:
    url: jdbc:oracle:thin:@192.168.31.99:1521/orcl
    username: RAINBOW
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
      time-zone: GMT+8
  redis:
    host: 192.168.31.99
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
    timeout: 0
    password:
  resources:
    static-locations: file://${beetl.base-root}static/
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    com.rainbow: DEBUG
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 85


rainbow:
  api:
    user:
      header:  101
      url:  chuxiong-rainbow.com

beetl:
  base-root: D:\webStormProjects\rainbow-manage-webapp\dist
  properties:
    DELIMITER_PLACEHOLDER_START: _{
    DELIMITER_STATEMENT_START: <!--#
    DELIMITER_STATEMENT_END: -->
    RESOURCE.root: /

